import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "../store/ReduxProvider";
import StyledComponentsRegistry from "../../../registry";
import CustomThemeProvider from "../theme/CustomThemeProvider";
import NextAuthProvider from "../component/NextauthProvider";
import { Locale } from "../../../i18n.config";
export const dynamic = "force-dynamic";

const inter = Inter({ subsets: ["latin"] });

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "ja" }];
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  publisher:'v-2023-09-12-2157'
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    locale?: Locale;
  };
};
export default function RootLayout({ children, params }: RootLayoutProps) {
  return (
    <html lang={params.locale ?? "en"} suppressHydrationWarning>
      <body className={inter.className}>
        <ReduxProvider>
          <NextAuthProvider>
            <StyledComponentsRegistry>
              <CustomThemeProvider>{children}</CustomThemeProvider>
            </StyledComponentsRegistry>
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
